insert clients (id, dni, name, lastname, email, lastdelivery, nextrenewal) values (1, 24299631, 'Gabriel', 'Gabriel', 'gabrielpinia@hotmail.com', CURDATE(), CURDATE());
insert clients (id, dni, name, lastname, email, lastdelivery, nextrenewal) values (2, 24299632, 'Jose', 'Jose', 'jose@hotmail.com', CURDATE(), CURDATE());
insert clients (id, dni, name, lastname, email, lastdelivery, nextrenewal) values (3, 24299633, 'Alejandro', 'Alejandro', 'alejandro@hotmail.com', CURDATE(), CURDATE());
insert clients (id, dni, name, lastname, email, lastdelivery, nextrenewal) values (4, 24299634, 'Maria', 'Maria', 'maria@hotmail.com', CURDATE(), CURDATE());
insert clients (id, dni, name, lastname, email, lastdelivery, nextrenewal) values (5, 24299635, 'Alexander', 'Alexander', 'alexander@hotmail.com', CURDATE(), CURDATE());
insert clients (id, dni, name, lastname, email, lastdelivery, nextrenewal) values (6, 24299636, 'Antony', 'Antony', 'antony@hotmail.com', CURDATE(), CURDATE());
insert clients (id, dni, name, lastname, email, lastdelivery, nextrenewal) values (7, 24299637, 'Luis', 'Luis', 'luis@hotmail.com', CURDATE(), CURDATE());
insert clients (id, dni, name, lastname, email, lastdelivery, nextrenewal) values (8, 24299638, 'Carlos', 'Carlos', 'carlos@hotmail.com', CURDATE(), CURDATE());
insert clients (id, dni, name, lastname, email, lastdelivery, nextrenewal) values (9, 24299639, 'Lina', 'Lina', 'lina@hotmail.com', CURDATE(), CURDATE());
insert clients (id, dni, name, lastname, email, lastdelivery, nextrenewal) values (10, 24299640, 'Ricardo', 'Ricardo', 'ricardo@hotmail.com', CURDATE(), CURDATE());
insert clients (id, dni, name, lastname, email, lastdelivery, nextrenewal) values (11, 24299641, 'Leon', 'Leon', 'leon@hotmail.com', CURDATE(), CURDATE());
insert clients (id, dni, name, lastname, email, lastdelivery, nextrenewal) values (12, 24299642, 'Ismael', 'Ismael', 'ismael@hotmail.com', CURDATE(), CURDATE());
insert clients (id, dni, name, lastname, email, lastdelivery, nextrenewal) values (13, 24299643, 'Diego', 'Diego', 'diego@hotmail.com', CURDATE(), CURDATE());
insert clients (id, dni, name, lastname, email, lastdelivery, nextrenewal) values (14, 24299644, 'Juan', 'Juan', 'juan@hotmail.com', CURDATE(), CURDATE());
insert clients (id, dni, name, lastname, email, lastdelivery, nextrenewal) values (15, 24299645, 'Anderson', 'Anderson', 'anderson@hotmail.com', CURDATE(), CURDATE());
insert clients (id, dni, name, lastname, email, lastdelivery, nextrenewal) values (16, 24299646, 'Enderson', 'Enderson', 'enderson@hotmail.com', CURDATE(), CURDATE());
insert clients (id, dni, name, lastname, email, lastdelivery, nextrenewal) values (17, 24299647, 'Adolfo', 'Adolfo', 'adolfo@hotmail.com', CURDATE(), CURDATE());
insert clients (id, dni, name, lastname, email, lastdelivery, nextrenewal) values (18, 24299648, 'Rodolfo', 'Rodolfo', 'rodolfo@hotmail.com', CURDATE(), CURDATE());
insert clients (id, dni, name, lastname, email, lastdelivery, nextrenewal) values (19, 24299649, 'Yhon', 'Yhon', 'yhon@hotmail.com', CURDATE(), CURDATE());
insert clients (id, dni, name, lastname, email, lastdelivery, nextrenewal) values (20, 24299650, 'Gerardo', 'Gerardo', 'gerardo@hotmail.com', CURDATE(), CURDATE());
insert clients (id, dni, name, lastname, email, lastdelivery, nextrenewal) values (21, 24299651, 'Rome', 'Rome', 'rome@hotmail.com', CURDATE(), CURDATE());
INSERT 	products (name, cost, minPrio) VALUES ('Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops', '109.95', 27);
INSERT 	products (name, cost, minPrio) VALUES ('Mens Casual Premium Slim Fit T-Shirts ', '22.3', 22);
INSERT 	products (name, cost, minPrio) VALUES ('Mens Cotton Jacket', '55.99', 25);
INSERT 	products (name, cost, minPrio) VALUES ('Mens Casual Slim Fit', '15.99', 30);
INSERT 	products (name, cost, minPrio) VALUES ('John Hardy Womens Legends Naga Gold & Silver Dragon Station Chain Bracelet', '695', 35);
INSERT  products (name, cost, minPrio) VALUES ('Solid Gold Petite Micropave ', '168', 65);
INSERT  products (name, cost, minPrio) VALUES ('White Gold Plated Princess', '9.99', 75);
INSERT  products (name, cost, minPrio) VALUES ('Pierced Owl Rose Gold Plated Stainless Steel Double', '10.99', 45);
INSERT  products (name, cost, minPrio) VALUES ('WD 2TB Elements Portable External Hard Drive - USB 3.0 ', '64', 95);
INSERT  products (name, cost, minPrio) VALUES ('SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s', '109', 62);
INSERT  products (name, cost, minPrio) VALUES ('Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5', '109', 45);
INSERT  products (name, cost, minPrio) VALUES ('WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive', '114', 75);
INSERT  products (name, cost, minPrio) VALUES ('Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin', '599', 15);
INSERT  products (name, cost, minPrio) VALUES ('Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED ', '999.99', 22);
INSERT  products (name, cost, minPrio) VALUES ('BIYLACLESEN Womens 3-in-1 Snowboard Jacket Winter Coats', '56.99', 30);
INSERT  products (name, cost, minPrio) VALUES ('Lock and Love Women\s Removable Hooded Faux Leather Moto Biker Jacket', '29.95', 23);
INSERT  products (name, cost, minPrio) VALUES ('Rain Jacket Women Windbreaker Striped Climbing Raincoats', '39.99', 66);
INSERT  products (name, cost, minPrio) VALUES ('MBJ Women\s Solid Short Sleeve Boat Neck V ', '9.85', 75);
INSERT  products (name, cost, minPrio) VALUES ('Opna Womens Short Sleeve Moisture', '7.95', 20);
INSERT  products (name, cost, minPrio) VALUES ('DANVOUY Womens T Shirt Casual Cotton Short', '12.99', 10);